"""
VoiceProtocol Constants for MyAICoach Backend Gateway.
Android VoiceProtocol.kt ile %100 birebir tutarlıdır.
"""

PROTOCOL_VERSION = 1

AUDIO_SAMPLE_RATE = 48_000
AUDIO_CHANNELS = 1
AUDIO_ENCODING = "PCM_16BIT"

# Client -> Server Message Types
MSG_START_TURN = "START_TURN"
MSG_AUDIO_INPUT_CHUNK = "AUDIO_INPUT_CHUNK"
MSG_END_USER_SPEECH = "END_USER_SPEECH"
MSG_CANCEL_TURN = "CANCEL_TURN"

# Server -> Client Message Types
MSG_TURN_STARTED = "TURN_STARTED"
MSG_TRANSCRIPT_RECEIVED = "TRANSCRIPT_RECEIVED"
MSG_LLM_TEXT_SEGMENT = "LLM_TEXT_SEGMENT"
MSG_AUDIO_OUTPUT_CHUNK = "AUDIO_OUTPUT_CHUNK"
MSG_TURN_METADATA = "TURN_METADATA"
MSG_TURN_COMPLETED = "TURN_COMPLETED"
MSG_TURN_CANCELLED = "TURN_CANCELLED"
MSG_ERROR_OCCURRED = "ERROR_OCCURRED"

# Standart Hata Kodları Kontratı
ERR_PROTOCOL_VERSION_UNSUPPORTED = "PROTOCOL_VERSION_UNSUPPORTED"
ERR_INVALID_MESSAGE = "INVALID_MESSAGE"
ERR_TURN_ALREADY_ACTIVE = "TURN_ALREADY_ACTIVE"
ERR_TURN_NOT_ACTIVE = "TURN_NOT_ACTIVE"
ERR_TURN_RATE_LIMITED = "TURN_RATE_LIMITED"
ERR_INVALID_AUDIO_FORMAT = "INVALID_AUDIO_FORMAT"
ERR_TURN_TIMED_OUT = "TURN_TIMED_OUT"
ERR_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
